# Generated by Django 2.0.5 on 2018-05-16 17:13

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='file',
            field=models.ImageField(upload_to=blog.models.blog_img_uh),
        ),
    ]
